### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /root/git/box-sfr-munin/script.php:137

### ISSUE THREAD

**Issue by birse29** [msklywenn/box-sfr-munin#1]
Hello,

Thx for the share of this code. I try to use it without munin first by setting manually ip & password

function graph($graph) {
    $ip = "myip";
    $password = "mypassword";

But when I run the script.php I am facing this issue: 

PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /data/box-sfr-munin/script.php:159
Stack trace:
#0 /data/box-sfr-munin/script.php(159): SimpleXMLElement->__construct()
#1 /data/box-sfr-munin/script.php(279): graph()
#2 {main}
  thrown in /data/box-sfr-munin/script.php on line 159

Can you help me please ?

Teddy

**Comment by msklywenn** [comment]
You should print curl's output to check what the box is sending you.
Turn `$ret = new SimpleXMLElement(curl_exec($ch));` into something like 
```php
$ret = curl_exec($ch);
echo $ret;
$ret = new $ret = SimpleXMLElement($ret);
```
